title: Vanessa Pereira # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  3+ years working on electronic health records specifications and functional analysis, with international experience. Possess a MSc in Medical Informatics from the Faculty of Medicine of Porto and a BSc in Medical instrumentation and computer engineering.Currently working as health informatics engineer openEHR clinical data modeller at Better. 
  <br><br>
  "The most courageous act is still to think for yourself. Aloud."
  <br><br>
  <a href="https://www.linkedin.com/in/vanessa-pereira-95b22949/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://twitter.com/VanessapPT">View My Twitter Profile</a> 
  <br><br>
  Quality of data saves lifes - I fight for it everyday.
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
