title: Vanessa Pereira
logo: /assets/img/logo.png
description:
  <br>
  10+ years working on electronic health records specifications and functional analysis, with international experience. 
  <br>
  <br>Medical computing instrumentation engineer. 
  <br>Possess a MSc in Medical Informatics by <a href="https://sigarra.up.pt/up/en/WEB_BASE.GERA_PAGINA?p_pagina=fmup">FMUP</a>. 
  <br>
  <br>Currently working as 
  <br>- Digital health engineer @ <a href="https://www.lih.lu">Luxembourg Institute of Health</a>.
  <br>- Clinical Program Board co-lead @ <a href="https://www.openehr.org">openEHR</a>.
  <br><br>
  <blockquote>
  "The most courageous act is still to think for yourself. Aloud."
  </blockquote>
  <br> 
  I believe quality and well structured health data saves lifes. And I fight for it, everyday.
  <br>
  <br>
cv:
  url: https://github.com/vanessa-pereira/vanessa-pereira.github.io/blob/master/cv/Vanessa_Pereira_CV.pdf
linkedin:
  url: https://www.linkedin.com/in/vanessa-pereira-95b22949
github:
  repository_url: https://github.com/vanessa-pereira
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
